layout_spectrum: 0.8025638
typography_spectrum: 0.1357109
color:
  saturation: 0.6559578
  lightness: 0.1958547
  brandStrength: 0.8957447
  brandColors:
    - '#0D0C0C'
    - '#5C4B41'
    - '#9A9079'
    - '#FFFFFF'
    - '#5CA2D8'
  rhythmicContrast: 0.9002726
name: www.caf.net.au
