collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6559578
  brandStrength: 1
  lightness: 0.1958547
  brandColors:
    - '#D9CDBD'
    - '#A58F78'
    - '#0C0603'
    - '#4C3827'
    - '#89705A'
  rhythmicContrast: 0.9002726
typography_spectrum: 0.1357109
layout_spectrum: 0.8025638
name: www.caf.net.au
