collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.6574468
color:
  saturation: 1
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#D9CDBD'
    - '#A58F78'
    - '#0C0603'
    - '#4C3827'
    - '#89705A'
  rhythmicContrast: 0.9002726
layout_spectrum: 0.8914894
name: www.caf.net.au
